services:
  - type: web
    name: Rag_Design
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python src/build_pipeline.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: STORAGE_DIR
        value: storage
